# Generated by Django 6.0.2 on 2026-03-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_stage',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начата'), ('cell_reg', 'Регистрация ячеек'), ('design', 'Разработка дизайна'), ('controls', 'Разработка контролей'), ('tables', 'Разработка выходных таблиц'), ('test_nsk', 'Тест НСК'), ('test_district', 'Тест район'), ('production', 'Промышленная эксплуатация')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
    ]
