# Generated by Django 6.0.2 on 2026-03-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_task_sub_stage_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfile',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskfile',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='CommentFile',
        ),
        migrations.DeleteModel(
            name='TaskFile',
        ),
    ]
