# Generated by Django 4.2.9 on 2026-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_taskfile_task_remove_taskfile_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начата'), ('development', 'Разработка'), ('test_nsk', 'Тест НСК'), ('test_district', 'Тест район'), ('production', 'Промышленная эксплуатация')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
    ]
