# Generated by Django 4.2.9 on 2026-03-02 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_alter_taskstatuslog_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='client_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Клиенты'),
        ),
    ]
